# Generated by Django 4.2.2 on 2023-08-22 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='travelers',
            new_name='places',
        ),
    ]
