# Generated by Django 4.2.2 on 2023-08-22 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_travelers_places'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='places',
            new_name='placess',
        ),
    ]
