# Generated by Django 4.2.2 on 2023-08-22 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_places_placess'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='placess',
            new_name='travelers',
        ),
    ]
